# -*- coding: utf-8 -*-
"""sentiment_description.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MH3KqdiuEBNHMdZNp6sPRHpanm4qZhq
"""

import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import sent_tokenize

# Only required on the first run
nltk.download('vader_lexicon')
nltk.download('punkt', force=True)
nltk.download('punkt_tab')

# Instantiate our analyzer
sid = SentimentIntensityAnalyzer()

# Load VADER lexicon
vader_lexicon = SentimentIntensityAnalyzer().lexicon

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/cleaned_womens_orgs_WI_FB.csv')

df.head(3)

df['account.pageDescription'] = df['account.pageDescription'].astype(str)

df['account.pageDescription_score'] = df['account.pageDescription'].apply(
    lambda x: sid.polarity_scores(x).get('compound', 0))

df[['account.name','account.pageDescription','account.pageDescription_score']].sample(5)

df.to_csv('/content/drive/My Drive/sentiment_description.csv', index=False)